### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by cwarner-mdsol**

### CODE REVIEW

**Comment by sjvermeu** [comment]
Would you mind if I reopen and apply? Or is there a particular reason why it was closed? I think they all make sense.

**Comment by cwarner-mdsol** [comment]
Yeah I actually ended up running through some more cleanups i'll submit a new PR a little later so you can cherry pick if necessary.

**Comment by sjvermeu** [comment]
Ah even better - thanks for your effort!

**Comment by cwarner-mdsol** [comment]
Yeah no problem.. needed it.. Thanks for putting this out there or I would have to had done it myself.. Saved me countless hours here.

**Pull request closed without merging**
